"""empty message

Revision ID: ddd51f2298ff
Revises: dbaa83512da9
Create Date: 2025-06-09 17:37:45.889733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd51f2298ff'
down_revision = 'dbaa83512da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=False))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=False))

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('cargo_capacity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('cargo_capacity')
        batch_op.drop_column('manufacturer')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('diameter')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###
